In [1]:
import pandas as pd
import numpy as np


In [ ]:
df= pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])
df.head()

#df.to_csv('Test1.csv') # converting into excel sheet...


Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [3]:
## Accessing the element

#1. .loc (focus on only row indexes)  2. .iloc (ocus on both rows and column indexes)
print(df.loc['Row1']) # printing first row and Name: Row1, dtype: int64 
print(type(df.loc['Row1'])) # type <class 'pandas.core.series.Series'>
# dataframes is the combination of many column :at least it should greater than one column and row  :: type is printing series because series means only one rows..not whole table


Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
print(df.iloc[:,:]) # print all rows
print(df.iloc[0:2,:])
print(df.iloc[0:2,0:2])
print(type(df.iloc[3:,4:]))# type of iloc is: <class 'pandas.core.frame.DataFrame


      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
      Column1  Column2
Row1        0        1
Row2        4        5
<class 'pandas.core.frame.DataFrame'>


In [5]:
# convert dataframes into array:---->

print(df.iloc[:,1:].values) # give value in array formate...
print(df.iloc[:,1:].values.shape) # shape of value is (5, 3)


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]
(5, 3)


In [6]:
# checking null condition::

print(df.isnull().sum) # in col1 have 0 null value,col2 have 0 null value as same at it....
print(df)
print(df['Column1'].value_counts()) # it give how many time a number is present..
print(df['Column1'].unique()) # give the unique value of col1:: [ 0  4  8 12 16]


<bound method DataFrame.sum of       Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False>
      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19
Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64
[ 0  4  8 12 16]


In [7]:
# we directly call col without using loc

print(df['Column3']) #Row1 2 , Row2 6 , Row3 10 , Row4 14 , Row5 18 Name: Column3, dtype: int64
print(df[['Column1','Column2']]) # o/p of both the column..

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Column3, dtype: int64
      Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17
