Data Cleaning:
is the process of deleting and correcting inaccurate , incomplete or inconsistance data

Techniques of data cleaning:

1. Handling Missing Values
   options:
   . Remove missing record
   . replace with mean/meadian
   . Replace with most frequent value
2. Correcting Inconsistance Data
3. Removing Duplicate Data
4. Handling Outliers


# Numpy

numerical python is used for:
. Fast mathemaatical operations
. Working arrays
. Handling large datasets efficiently

Why NumPy ?

. Faster than python lists
.less memory
. support vectorized


In [1]:
# NumPy and Pandas

import numpy as np

In [2]:
a = np.array([1, 2, 8, 40, 56])
print(a)

[ 1  2  8 40 56]


In [3]:
# 2D array
b= np.array([[1,2,3] , [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c= a + 5 # element-wise addition in the above array
print(c)

d= a*3 # element-wise multiplication in the above array
print(d)    

[ 6  7 13 45 61]
[  3   6  24 120 168]


In [5]:
print("Mean" , np.mean(a)) # mean of the array
print("Median" , np.median(a)) # median of the array

print("Sum : ", np.sum(a)) # sum of the array
print("Maximum :" , np.max(a)) # maximum value in the array
print("Minimum :" , np.min(a)) # minimum value in the array

Mean 21.4
Median 8.0
Sum :  107
Maximum : 56
Minimum : 1


In [6]:
# indexing
arr = np.array([10, 20, 30, 40 , 50])
print(arr[3])

# slicing
print(arr[0:3]) # slicing from index 0 to 2 (3 is exclusive)  
print(arr[2:]) # slicing from index 2 to the end of the array
print(arr[:4]) # slicing from the beginning of the array to index 3 (4
print(arr[-3:-1]) # slicing the last 3 elements of the array

40
[10 20 30]
[30 40 50]
[10 20 30 40]
[30 40]


# PANDAS

Pandas is used for:
. Data manipulation and analysis
. Handling structured data (tables)
. Working with CSV , Excel files


In [7]:
import pandas as pd

In [8]:
data ={
    'Name': ['Aman' , 'Riya' , 'Kriti' , 'Rahul'],
    'Marks': [85, 92, 78, 90],
    'Age': [18,17,19,18]
}

In [9]:
df = pd.DataFrame(data)

In [10]:
print(df)

    Name  Marks  Age
0   Aman     85   18
1   Riya     92   17
2  Kriti     78   19
3  Rahul     90   18


In [11]:
print(df.shape) # shape of the DataFrame (number of rows, number of columns)

print(df.columns) # column names of the DataFram

print(40*"__")

print(df.info()) # information about the DataFrame (data types, non-null values, memory usage)

(4, 3)
Index(['Name', 'Marks', 'Age'], dtype='object')
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Marks   4 non-null      int64 
 2   Age     4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
None


In [12]:
print(df[["Name", "Age"]]) # accessing specific columns of the DataFrame

    Name  Age
0   Aman   18
1   Riya   17
2  Kriti   19
3  Rahul   18


In [13]:
filtered = df[df["Marks"]>80] # filtering rows based on a condition
print(filtered)

    Name  Marks  Age
0   Aman     85   18
1   Riya     92   17
3  Rahul     90   18


In [14]:
df["Passed"] = df["Marks"] > 80 # adding a new column to the DataFrame based on a condition
print(df)

    Name  Marks  Age  Passed
0   Aman     85   18    True
1   Riya     92   17    True
2  Kriti     78   19   False
3  Rahul     90   18    True


In [15]:
df_sort = df.sort_values(by="Marks", ascending=False) # sorting the DataFrame by the "Marks" column in descending order
print(df_sort)

    Name  Marks  Age  Passed
1   Riya     92   17    True
3  Rahul     90   18    True
0   Aman     85   18    True
2  Kriti     78   19   False


In [16]:
# get the info of the first row of the DataFrame 

df.iloc[0] # accessing the first row of the DataFrame


Name      Aman
Marks       85
Age         18
Passed    True
Name: 0, dtype: object